# Generated by Django 5.1.7 on 2025-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryout',
            name='status',
            field=models.BooleanField(choices=[(True, 'Submitted'), (False, 'Draft')], default=False),
        ),
    ]
