# Generated by Django 5.1.7 on 2025-03-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tryout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tryout',
            name='description',
        ),
        migrations.AddField(
            model_name='tryout',
            name='category',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
